---
- name: Juice Shop | Download
  ansible.builtin.get_url: 
    url: "{{ juice_shop_download_url }}"
    dest: "{{ home_path }}/{{ juice_shop_download_version }}.tgz"

- name: Juice Shop | Create dest folder
  ansible.builtin.file:
    path: "{{ juice_shop_dest_dir }}"
    state: directory
    mode: "0755"

- name: Juice Shop | Extract tgz file
  ansible.builtin.unarchive:
    src: "{{ home_path }}/{{ juice_shop_download_version }}.tgz"
    dest: "{{ juice_shop_dest_dir }}"
    remote_src: yes

- name: Juice Shop | Install packages based on package.json
  community.general.npm:
    path: "{{ juice_shop_home }}"

- name: Juice Shop | Move juice_shop.service template
  ansible.builtin.template:
    src: "template{{ juice_shop_service }}"
    dest: /etc/systemd/system/juiceshop.service
    owner: root
    mode: u=rw,g=r,o=r
    
- name: Juice Shop | Daemon reload and service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: juiceshop